import { useEffect, useState, FormEvent } from 'react'
import { supabase } from './lib/supabase'
import type { CampaignApplication } from './types'
type Content = { id: string; application_id: string; title: string; content_url: string; status: string; review_note: string | null; post_url: string | null }
type Message = { id: number; sender_id: string; body: string; created_at: string }
export function CreatorDeliveries({ applications }: { applications: CampaignApplication[] }) {
 const [items,setItems]=useState<Content[]>([]),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false)
 const ids=applications.map(a=>a.id).join(',')
 const load=async()=>{if(!ids)return;const {data,error}=await supabase.from('campaign_content').select('*').in('application_id',ids.split(','));if(error)setNotice(error.message);else setItems(data||[])}
 useEffect(()=>{load();const t=setInterval(load,10000);return()=>clearInterval(t)},[ids])
 async function submit(e:FormEvent<HTMLFormElement>,aid:string){e.preventDefault();const form=e.currentTarget;const f=new FormData(form);setBusy(true);const {error}=await supabase.rpc('submit_creator_content',{aid,title:String(f.get('title')),url:String(f.get('url'))});setNotice(error?error.message:'Content sent to the company for review.');if(!error){form.reset();await load()}setBusy(false)}
return <div className="collaboration-workspace">{notice&&<p className="form-notice">{notice}</p>}{applications.map(a=><section key={a.id} className="collaboration-card"><h3>{a.campaigns?.name}</h3><p>Delivery stage: {a.lifecycle?.replace(/_/g,' ')||'confirmed'} · Deadline: {a.content_deadline||'Not set'}</p>{a.brand_note&&<p><b>Company note:</b> {a.brand_note}</p>}{a.status==='accepted'&&<form onSubmit={e=>submit(e,a.id)}><label className="field"><span>Submission title</span><input name="title" required placeholder="Reel draft — version 1"/></label><label className="field"><span>Content link</span><input name="url" required type="url" pattern="https://.*" placeholder="https://…"/></label><button className="primary-button" disabled={busy}>Submit for review</button></form>}{items.filter(i=>i.application_id===a.id).map(i=><div className="collaboration-item" key={i.id}><strong>{i.title} · {i.status}</strong><p><a href={i.content_url} target="_blank" rel="noreferrer">View submitted content ↗</a></p>{i.review_note&&<p>{i.review_note}</p>}{i.post_url&&<a href={i.post_url} target="_blank" rel="noreferrer">Published post ↗</a>}{i.status==='approved'&&<form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const {error}=await supabase.rpc('publish_creator_content',{content_id:i.id,url:String(f.get('post_url'))});setNotice(error?error.message:'Published post link saved for the company.');await load()}}><label className="field"><span>Published post URL</span><input name="post_url" type="url" pattern="https://.*" required/></label><button className="primary-button">Share published post</button></form>}</div>)}</section>)}</div>
}
export function CreatorMessages({applications}:{applications:CampaignApplication[]}){
 const available=applications.filter(a=>a.campaigns?.company_id),[selected,setSelected]=useState(''),[messages,setMessages]=useState<Message[]>([]),[notice,setNotice]=useState(''),[uid,setUid]=useState('');const app=available.find(a=>a.id===selected)||available[0]
 const load=async()=>{if(!app)return;const {data,error}=await supabase.from('campaign_messages').select('*').eq('application_id',app.id).order('created_at');if(error)setNotice(error.message);else setMessages(data||[])}
 useEffect(()=>{supabase.auth.getUser().then(({data})=>setUid(data.user?.id||''));load();const t=setInterval(load,8000);return()=>clearInterval(t)},[app?.id])
 if(!available.length)return <p>No company conversations yet. Apply to a company campaign to start a conversation.</p>
 return <section className="collaboration-card"><label className="field"><span>Campaign conversation</span><select value={app.id} onChange={e=>setSelected(e.target.value)}>{available.map(a=><option key={a.id} value={a.id}>{a.campaigns?.brand_name} — {a.campaigns?.name}</option>)}</select></label><div className="creator-message-thread">{messages.map(m=><div key={m.id} className={m.sender_id===uid?'own':''}><small>{m.sender_id===uid?'You':'Company'}</small><p>{m.body}</p></div>)}</div><form onSubmit={async e=>{e.preventDefault();const f=e.currentTarget;const body=String(new FormData(f).get('body'));const contact=await supabase.rpc('creator_campaign_contact',{cid:app.campaign_id});if(contact.error||!contact.data){setNotice(contact.error?.message||'Company contact is unavailable.');return}const {error}=await supabase.from('campaign_messages').insert({campaign_id:app.campaign_id,application_id:app.id,sender_id:uid,recipient_id:contact.data,body});setNotice(error?error.message:'');if(!error){f.reset();await load()}}}><label className="field"><span>Your message</span><textarea name="body" required maxLength={4000}/></label><button className="primary-button">Send message</button></form>{notice&&<p className="form-notice">{notice}</p>}</section>
}
export function CreatorPaymentRecords(){const [records,setRecords]=useState<{id:string;amount:number;status:string;reference:string|null}[]>([]);useEffect(()=>{supabase.from('company_payments').select('id,amount,status,reference').then(({data})=>setRecords(data||[]))},[]);return <section className="collaboration-card"><h3>Company payment records</h3><p>Payments recorded by companies. These are payment records, not an IVRE wallet balance.</p>{records.map(r=><div className="collaboration-item" key={r.id}>₹{Number(r.amount).toLocaleString('en-IN')} · {r.status} · {r.reference||'No reference'}</div>)}{!records.length&&<p>No company payments recorded yet.</p>}</section>}
