import React, { useEffect, useState } from 'react';
import { db, checked } from './lib';
import { safeMediaUrl } from './commerce';

export default function Marketplace({ company, page, navigate }) {
 const [cards,setCards]=useState([]),[profile,setProfile]=useState(null),[cart,setCart]=useState(null),[brief,setBrief]=useState({product:'',objective:'',audience:'',instructions:'',deadline:''});
 const [busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[consent,setConsent]=useState(false);
 const id=new URLSearchParams(location.search).get('creator');
 async function refreshCart(){setCart(await checked(db.rpc('marketplace_cart',{cid:company.id})));}
 async function run(fn){setBusy(true);setNotice('');try{await fn()}catch(e){setNotice(e.message||'Please try again.')}finally{setBusy(false)}}
 useEffect(()=>{let live=true;(async()=>{
  setNotice('');setProfile(null);setCart(null);setConsent(false);setBusy(true);
  try {
   if(page==='Marketplace') {
    if(id){const p=await checked(db.rpc('marketplace_profile',{profile_id:id}));if(live)setProfile(p)}
    else {const rows=await checked(db.rpc('marketplace_featured'));if(live)setCards(rows)}
   }else{
    const [c,b]=await Promise.all([checked(db.rpc('marketplace_cart',{cid:company.id})),checked(db.from('marketplace_cart_briefs').select('*').eq('company_id',company.id).maybeSingle())]);
    if(live){setCart(c);setBrief({product:'',objective:'',audience:'',instructions:'',...b,deadline:b?.deadline||''})}
   }
  }catch(e){if(live)setNotice(e.message)}finally{if(live)setBusy(false)}
 })();return()=>{live=false}},[company.id,page,id]);
 function openProfile(creator){const u=new URL(location.href);u.searchParams.set('creator',creator);u.searchParams.set('page','Marketplace');location.assign(u.href)}
 function browse(){const u=new URL(location.href);u.searchParams.delete('creator');u.searchParams.set('page','Marketplace');history.replaceState(null,'',u);navigate('Marketplace')}
 async function add(pkg){await run(async()=>{await checked(db.from('marketplace_cart_items').upsert({company_id:company.id,package_id:pkg.id,quantity:1},{onConflict:'company_id,package_id',ignoreDuplicates:true}));setNotice('Added to your campaign cart.');})}
 const price=(n)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',minimumFractionDigits:2}).format(n);
 const formComplete=brief.product.trim()&&brief.objective.trim()&&brief.audience.trim()&&brief.deadline;
 return <section className="commerce-page">
  <div className="commerce-heading"><div><small>IVRE MARKETPLACE</small><h1>{page==='Marketplace'?'Meet your next collaborator.':page==='Cart'?'Your campaign cart.':'Clear scope. Confident checkout.'}</h1><p>{page==='Marketplace'?'Real creator profiles. Clear packages. No subscription required to hire.':'Choose the work, agree the brief, and review every charge.'}</p></div><button onClick={()=>page==='Marketplace'?navigate('Cart'):browse()}>{page==='Marketplace'?'View cart':'Browse creators'}</button></div>
  {notice&&<div className="notice" role="status">{notice}</div>}
  {busy&&<p role="status">Loading your marketplace…</p>}
  {page==='Marketplace'&&!profile&&!busy&&!id&&<div className="commerce-grid">{cards.length?cards.map(c=><article className="commerce-card" key={c.id}>{safeMediaUrl(c.avatar_url)&&<img src={safeMediaUrl(c.avatar_url)} alt={c.full_name} loading="lazy" referrerPolicy="no-referrer"/>}<small>{(c.niches||[]).join(' · ')}</small><h2>{c.full_name}</h2><p>{c.location}</p><strong>From {price(c.display_price)}</strong><button onClick={()=>openProfile(c.id)}>View profile →</button></article>):<div className="panel"><h2>Creator storefronts are opening.</h2><p>Published creator profiles will appear here. We never substitute sample creators for real results.</p><a href="https://app.ivre.in/">Create your creator profile</a></div>}</div>}
  {page==='Marketplace'&&profile&&<>
   <div className="commerce-profile"><div>{safeMediaUrl(profile.avatar_url)&&<img className="commerce-avatar" src={safeMediaUrl(profile.avatar_url)} alt={profile.full_name}/>}<small>{profile.published?'CREATOR PROFILE':'DRAFT PREVIEW'}</small><h2>{profile.full_name}</h2><p>{profile.location} · {(profile.languages||[]).join(', ')}</p><p>{profile.bio}</p><div className="commerce-metrics"><span><b>{Number(profile.follower_count).toLocaleString('en-IN')}</b> followers</span><span><b>{profile.engagement_rate}%</b> engagement</span><span>{profile.availability}</span></div><small>Statistics are creator-provided, not independently verified.</small></div><aside className="panel"><h3>Previous brand work</h3><p>{profile.previous_work||'No previous work description supplied.'}</p><h3>Specialities</h3><p>{(profile.niches||[]).join(' · ')}</p></aside></div>
   <h2>Portfolio</h2><div className="commerce-grid">{(profile.assets||[]).map(a=><article key={a.id} className="commerce-card">{safeMediaUrl(a.url)&&(a.kind==='image'?<img src={safeMediaUrl(a.url)} alt={a.caption} loading="lazy" referrerPolicy="no-referrer"/>:a.kind==='video'?<video src={safeMediaUrl(a.url)} controls preload="none"/>:<a href={safeMediaUrl(a.url)} target="_blank" rel="noopener noreferrer">View reel or portfolio ↗</a>)}<p>{a.caption}</p></article>)}</div>
   <h2>Choose a package</h2><div className="commerce-grid">{profile.packages.map(p=><article className="commerce-card" key={p.id}><small>{p.platform} · {p.delivery_days} days</small><h3>{p.title}</h3><p>{p.deliverables}</p><p>{p.requires_post?'Includes publishing on the creator account.':'Final asset delivery; no public post required.'}</p><p>Usage: {p.usage_rights}</p><p>Initial submission + one revision.</p><strong>{price(p.display_price)}</strong><small>Includes creator-side IVRE fee. Company fee and applicable tax shown at checkout.</small><button disabled={busy||profile.availability==='booked'} onClick={()=>add(p)}>{profile.availability==='booked'?'Currently unavailable':'Add to cart'}</button></article>)}</div>
  </>}
  {page!=='Marketplace'&&cart&&<div className="commerce-checkout"><div>
   {!cart.items.length?<div className="panel"><h2>Your cart is empty.</h2><p>Open a creator profile and choose a service package.</p><button onClick={()=>navigate('Marketplace')}>Browse creators</button></div>:cart.items.map(item=><article key={item.package_id} className="commerce-cart-item"><div><small>{item.creator_name} · {item.platform}</small><h3>{item.title}</h3><p>{item.deliverables}</p><p>{item.delivery_days} days · {item.requires_post?'Posting required':'Content delivery only'}</p><small>{item.usage_rights}</small>{!item.available&&<p role="alert">This package is currently unavailable. Remove it before checkout.</p>}</div><div><strong>{price(item.display_price)} each</strong><label>Quantity<select disabled={busy} value={item.quantity} onChange={e=>{const quantity=Number(e.target.value);run(async()=>{await checked(db.from('marketplace_cart_items').update({quantity}).eq('company_id',company.id).eq('package_id',item.package_id));await refreshCart()})}}>{Array.from({length:20},(_,i)=><option key={i+1}>{i+1}</option>)}</select></label><button disabled={busy} className="secondary" onClick={()=>run(async()=>{await checked(db.from('marketplace_cart_items').delete().eq('company_id',company.id).eq('package_id',item.package_id));await refreshCart()})}>Remove</button></div></article>)}
   {page==='Checkout'&&cart.items.length>0&&<form className="panel" onSubmit={e=>{e.preventDefault();run(async()=>{const {company_id,product,objective,audience,instructions,deadline}=brief;await checked(db.from('marketplace_cart_briefs').upsert({company_id:company.id,product,objective,audience,instructions,deadline:deadline||null,updated_at:new Date().toISOString()}));setNotice('Campaign brief saved. No payment has been taken.')})}}><h2>Your campaign brief</h2>{[['product','Product / brand',500],['objective','Campaign objective',2000],['audience','Target audience',2000],['instructions','References and special instructions',6000]].map(([key,label,max])=><label className="field" key={key}>{label}<textarea required={key!=='instructions'} maxLength={max} value={brief[key]} onChange={e=>setBrief({...brief,[key]:e.target.value})}/></label>)}<label className="field">Required delivery date<input type="date" min={new Date().toISOString().slice(0,10)} value={brief.deadline} required onChange={e=>setBrief({...brief,deadline:e.target.value})}/></label><button disabled={busy}>Save campaign brief</button></form>}
  </div><aside className="commerce-summary"><small>YOUR ORDER SUMMARY</small><h2>Every fee, upfront.</h2><dl><dt>Creator packages</dt><dd>{price(cart.package_total)}</dd><dt>Company platform fee</dt><dd>{price(cart.company_fee)}</dd><dt>Subtotal before tax</dt><dd>{price(cart.subtotal)}</dd><dt>GST</dt><dd>Not yet calculated</dd><dt>Final payable</dt><dd>Awaiting tax configuration</dd></dl><p>Package prices include a 10% creator-side markup. The company fee is another 10% of creator earnings, not of the marked-up price.</p>{page==='Cart'?<button disabled={!cart.items.length||cart.items.some(i=>!i.available)||busy} onClick={()=>navigate('Checkout')}>Continue to checkout →</button>:<><label><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/> I have reviewed the brief, usage rights and replacement-first terms below.</label><button type="button" disabled={!cart.payment_enabled||!consent||!formComplete||!cart.items.length||busy} aria-describedby="payment-readiness">Pay securely with Razorpay</button></>}<p id="payment-readiness" role="status">{cart.payment_notice}</p><p>Collected by UKIYOAI PRIVATE LIMITED for IVRE. Money is released to creators only under the approved delivery and settlement arrangement.</p><details><summary>Revisions and replacement terms</summary><p>One revision is included. After two distinct rejected submissions, IVRE reviews the evidence. If the claim is upheld, we seek a replacement first. If none is agreed within seven days, the creator-package allocation is refundable under the final approved terms; the company-side fee is retained where permitted. Tax adjustments remain subject to the approved invoice policy.</p></details></aside></div>}
 </section>
}
